-- Quick setup script for PostgreSQL database
-- This script performs all setup in one go

-- Start transaction
BEGIN;

-- Create tables if they don't exist
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" text NOT NULL,
    "FirstName" character varying(100),
    "LastName" character varying(100),
    "Phone" character varying(20),
    "Designation" character varying(100),
    "Organization" character varying(200),
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone,
    "UserName" character varying(256) NOT NULL,
    "NormalizedUserName" character varying(256) NOT NULL,
    "Email" character varying(256) NOT NULL,
    "NormalizedEmail" character varying(256) NOT NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NOT NULL,
    "NormalizedName" character varying(256) NOT NULL,
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "RoleClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" character varying(256),
    "ClaimValue" character varying(256),
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" character varying(256),
    "ClaimValue" character varying(256),
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" character varying(256),
    "UserId" text NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- Create indexes
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "Users" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "Users" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "Roles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

-- Seed roles
INSERT INTO "Roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
VALUES 
    ('admin-role-id', 'Admin', 'ADMIN', 'admin-stamp'),
    ('me-officer-role-id', 'M&E Officer', 'M&E OFFICER', 'me-officer-stamp'),
    ('field-officer-role-id', 'Field Officer', 'FIELD OFFICER', 'field-officer-stamp')
ON CONFLICT ("Id") DO NOTHING;

-- Commit transaction
COMMIT;

-- Display setup summary
SELECT 
    'Database setup completed successfully!' as status,
    (SELECT COUNT(*) FROM "Roles") as roles_created,
    (SELECT COUNT(*) FROM "Users") as users_created,
    (SELECT COUNT(*) FROM "UserRoles") as role_assignments;